# Define o servidor HTTP que o Nginx usara para servir o frontend Angular.
server {
    # Faz o Nginx escutar na porta 80 dentro do container.
    listen 80;

    # Define a pasta onde os arquivos finais do Angular ficam dentro da imagem.
    root /usr/share/nginx/html;

    # Define o arquivo inicial que sera servido quando acessar a raiz do frontend.
    index index.html;

    # Intercepta chamadas feitas pelo Angular para caminhos iniciados com /api/.
    location /api/ {
        # Encaminha /api/weatherforecast para http://host.docker.internal:8082/weatherforecast.
        proxy_pass http://host.docker.internal:8082/;

        # Usa HTTP 1.1 no proxy para manter compatibilidade com APIs modernas.
        proxy_http_version 1.1;

        # Repassa o host original da requisicao para a API.
        proxy_set_header Host $host;

        # Repassa o IP do cliente que acessou o frontend.
        proxy_set_header X-Real-IP $remote_addr;

        # Repassa a cadeia de IPs envolvidos na requisicao.
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # Repassa o protocolo usado pelo cliente na chamada original.
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Serve os arquivos do Angular e redireciona rotas internas para index.html.
    location / {
        # Tenta encontrar arquivo/pasta real; se nao encontrar, entrega o index.html do Angular.
        try_files $uri $uri/ /index.html;
    }
}
